FROM docker.elastic.co/beats/filebeat:7.10.0

COPY filebeat_manticore.yml /usr/share/filebeat/filebeat.yml
COPY run_manticore.sh ./run_manticore.sh
USER root
RUN chown filebeat /usr/share/filebeat/filebeat.yml
USER filebeat

ENTRYPOINT ["run_manticore.sh"]