FROM docker.elastic.co/beats/filebeat:7.10.0

COPY filebeat_es.yml /usr/share/filebeat/filebeat.yml
COPY run_es.sh ./run_es.sh
USER root
RUN chown filebeat /usr/share/filebeat/filebeat.yml
USER filebeat

ENTRYPOINT ["run_es.sh"]