filebeat.inputs:
- type: log
  id: nginx-main
  paths:
    - /logs/nginx_main.log
- type: log
  id: nginx-delta
  paths:
    - /logs/nginx_delta.log

processors:
- dissect:
    tokenizer: '%{ip} - %{username} [%{time_local}] "%{request_method} %{request_path}" %{status|integer} %{bytes_sent|integer} "%{referer}" "%{http_user_agent|string}/%{http_user_agent_version|string}"'
    target_prefix: ""

output.elasticsearch:
  hosts: ["http://elastic-for-kibana:9200"]
  pipeline: preprocess
  index:  "test"
  allow_older_versions: true
  bulk_max_size: 10000

setup.ilm:
  enabled: false

setup.template:
  name: "test"
  pattern: "test"

setup.template.overwrite: true

seccomp:
  default_action: allow
  syscalls:
  - action: allow
    names:
    - rseq
